package Interfaces;

import Classes.General.Button;
import Classes.RealEstate.SortedList;
import Classes.UserLogin.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

public class frmAddNewUser extends javax.swing.JInternalFrame {    
    
    private ListUserLogin userLogin;
    private static SortedList list = new SortedList();
    UserLoginXML userLoginXml = new UserLoginXML();
    private static frmAddNewUser instance;      
    
    public frmAddNewUser() {
        
        initComponents();
        this.setResizable(false);
        this.setFrameIcon(new ImageIcon(getClass().getResource("/Images/AddUser.png")));
    }
    
    public static frmAddNewUser GetInstance() 
    {
        if (instance == null) 
        {
            instance = new frmAddNewUser();
        }
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddNewUser = new javax.swing.JPanel();
        jLabelNewUserName = new javax.swing.JLabel();
        jLabelPwd = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jTxtNewPwd = new javax.swing.JTextField();
        jLabelConfirmPwd = new javax.swing.JLabel();
        jTxtConfirmPwd = new javax.swing.JTextField();
        jBtnSubmit = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Add New User");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabelNewUserName.setText("User Name");

        jLabelPwd.setText("Password");

        jLabelConfirmPwd.setText("Confirm Password");

        jBtnSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSubmit.setText("Submit");
        jBtnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSubmitMouseExited(evt);
            }
        });
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jBtnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancel.setText("Cancel");
        jBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCancelMouseExited(evt);
            }
        });
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddNewUserLayout = new javax.swing.GroupLayout(jPanelAddNewUser);
        jPanelAddNewUser.setLayout(jPanelAddNewUserLayout);
        jPanelAddNewUserLayout.setHorizontalGroup(
            jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddNewUserLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNewUserName)
                    .addComponent(jLabelPwd)
                    .addComponent(jLabelConfirmPwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtNewPwd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtConfirmPwd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanelAddNewUserLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanelAddNewUserLayout.setVerticalGroup(
            jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddNewUserLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewUserName)
                    .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPwd)
                    .addComponent(jTxtNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmPwd)
                    .addComponent(jTxtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanelAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSubmit)
                    .addComponent(jBtnCancel))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSubmitMouseEntered
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnSubmit, "Entry");
    }//GEN-LAST:event_jBtnSubmitMouseEntered

    private void jBtnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSubmitMouseExited
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnSubmit, "Exit");
    }//GEN-LAST:event_jBtnSubmitMouseExited

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed

        try {
            userLogin = userLoginXml.getUserLogin(jTxtUserName.getText(), jTxtNewPwd.getText());
            if (list.isThereHouse(userLogin)) {
                JOptionPane.showMessageDialog(rootPane, "User name already in use");
            } else {
                list.insertHouse(userLogin);
                userLoginXml.saveToUserLoginXML();
                JOptionPane.showMessageDialog(rootPane, "User credentials added to list");
            }
        } catch (NumberFormatException badHouseData) {
            // Text field info incorrectly formated
            JOptionPane.showMessageDialog(rootPane, "Number? " + badHouseData.getMessage());
        }
    }//GEN-LAST:event_jBtnSubmitActionPerformed

    private void jBtnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMouseEntered
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnCancel, "Entry");
    }//GEN-LAST:event_jBtnCancelMouseEntered

    private void jBtnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMouseExited
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnCancel, "Exit");
    }//GEN-LAST:event_jBtnCancelMouseExited

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      // Start, Button formatting
      jBtnSubmit.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
      jBtnCancel.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
      // End, Button formatting
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JLabel jLabelConfirmPwd;
    private javax.swing.JLabel jLabelNewUserName;
    private javax.swing.JLabel jLabelPwd;
    private javax.swing.JPanel jPanelAddNewUser;
    private javax.swing.JTextField jTxtConfirmPwd;
    private javax.swing.JTextField jTxtNewPwd;
    private javax.swing.JTextField jTxtUserName;
    // End of variables declaration//GEN-END:variables
}
