package Interfaces;

import Classes.General.Button;
import Classes.RealEstate.SortedList;
import Classes.UserLogin.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

public class frmChangePassword extends javax.swing.JInternalFrame {
        
    private ListUserLogin userLogin;
    private static SortedList list = new SortedList();
    UserLoginXML userLoginXml = new UserLoginXML();
    private static frmChangePassword instance;
   
    public frmChangePassword() {
        
        initComponents();
        this.setResizable(false);
        this.setFrameIcon(new ImageIcon(getClass().getResource("/Images/Change Password.png")));
    }
    
    public static frmChangePassword GetInstance() 
    {
        if (instance == null) 
        {
            instance = new frmChangePassword();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelChngPwd = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelOldPwd = new javax.swing.JLabel();
        jLabelNewPwd = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jLabelConfirmPwd = new javax.swing.JLabel();
        jBtnSubmit = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jNewPwd = new javax.swing.JPasswordField();
        jCnfrmPwd = new javax.swing.JPasswordField();
        jOldPwd = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Change Password");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabelUserName.setText("User Name");

        jLabelOldPwd.setText("Old Password");

        jLabelNewPwd.setText("New Password");

        jLabelConfirmPwd.setText("Confirm Password");

        jBtnSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSubmit.setText("Submit");
        jBtnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSubmitMouseExited(evt);
            }
        });
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jBtnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancel.setText("Cancel");
        jBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCancelMouseExited(evt);
            }
        });
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelChngPwdLayout = new javax.swing.GroupLayout(jPanelChngPwd);
        jPanelChngPwd.setLayout(jPanelChngPwdLayout);
        jPanelChngPwdLayout.setHorizontalGroup(
            jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChngPwdLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChngPwdLayout.createSequentialGroup()
                        .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName)
                            .addComponent(jLabelOldPwd)
                            .addComponent(jLabelNewPwd)
                            .addComponent(jLabelConfirmPwd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtUserName)
                            .addComponent(jNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCnfrmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelChngPwdLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jBtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(20, 20, 20))
        );
        jPanelChngPwdLayout.setVerticalGroup(
            jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChngPwdLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOldPwd)
                    .addComponent(jOldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewPwd)
                    .addComponent(jNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmPwd)
                    .addComponent(jCnfrmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelChngPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSubmit)
                    .addComponent(jBtnCancel))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChngPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChngPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSubmitMouseEntered
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnSubmit, "Entry");
    }//GEN-LAST:event_jBtnSubmitMouseEntered

    private void jBtnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSubmitMouseExited
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnSubmit, "Exit");
    }//GEN-LAST:event_jBtnSubmitMouseExited

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
        
        String oldPwd = String.copyValueOf(jOldPwd.getPassword());
        String newPwd = String.copyValueOf(jNewPwd.getPassword());
        String cnfrmPwd = String.copyValueOf(jCnfrmPwd.getPassword());
        Boolean showErrorMessage=false;

        if (jTxtUserName.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your user name.", "Error", JOptionPane.ERROR_MESSAGE);
            showErrorMessage = true;
            return;
        } else if (oldPwd.equals(null) || oldPwd.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your current password.", "Error", JOptionPane.ERROR_MESSAGE);
            showErrorMessage = true;
            return;
        }else if (newPwd.equals(null) || newPwd.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your new password.", "Error", JOptionPane.ERROR_MESSAGE);
            showErrorMessage = true;
            return;
        }else if (cnfrmPwd.equals(null) || cnfrmPwd.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please confirm your new password.", "Error", JOptionPane.ERROR_MESSAGE);
            showErrorMessage = true;
            return;
        }else if (!cnfrmPwd.equals(newPwd)) {
            JOptionPane.showMessageDialog(rootPane, "Passwords are not identical. Please confirm your new password.", "Error", JOptionPane.ERROR_MESSAGE);
            showErrorMessage = true;
            return;
        }
        
        if (!showErrorMessage) {
            try {
                userLogin = userLoginXml.getUserLogin(jTxtUserName.getText(), jNewPwd.getPassword().toString());
                if (list.isThereHouse(userLogin)) {
                    JOptionPane.showMessageDialog(rootPane, "User name already in use");
                } else {
                    list.insertHouse(userLogin);
                    userLoginXml.saveToUserLoginXML();
                    JOptionPane.showMessageDialog(rootPane, "User credentials added to list");
                }
            } catch (NumberFormatException badHouseData) {
                // Text field info incorrectly formated
                JOptionPane.showMessageDialog(rootPane, "Number? " + badHouseData.getMessage());
            }
        }
    }//GEN-LAST:event_jBtnSubmitActionPerformed

    private void jBtnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMouseEntered
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnSubmit, "Entry");
    }//GEN-LAST:event_jBtnCancelMouseEntered

    private void jBtnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMouseExited
        Button ob = new Button();
        ob.paint(getGraphics(), jBtnSubmit, "Exit");
    }//GEN-LAST:event_jBtnCancelMouseExited

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      // Start, Button formatting
      jBtnSubmit.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
      jBtnCancel.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
      // End, Button formatting
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JPasswordField jCnfrmPwd;
    private javax.swing.JLabel jLabelConfirmPwd;
    private javax.swing.JLabel jLabelNewPwd;
    private javax.swing.JLabel jLabelOldPwd;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPasswordField jNewPwd;
    private javax.swing.JPasswordField jOldPwd;
    private javax.swing.JPanel jPanelChngPwd;
    private javax.swing.JTextField jTxtUserName;
    // End of variables declaration//GEN-END:variables
}
