package Interfaces;

import Classes.General.Button;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

public class SearchLotNumber extends javax.swing.JDialog {

    public SearchLotNumber(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
    }

    SearchLotNumber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSearchPanel = new javax.swing.JPanel();
        jLabelLotNo = new javax.swing.JLabel();
        jTxtSearchLotNo = new javax.swing.JTextField();
        jBtnLotNoSearch = new javax.swing.JButton();
        jBtnCloseSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Lot Number");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelLotNo.setText("Lot Number");

        jBtnLotNoSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnLotNoSearch.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLotNoSearch.setText("Search");
        jBtnLotNoSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLotNoSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLotNoSearchMouseExited(evt);
            }
        });
        jBtnLotNoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLotNoSearchActionPerformed(evt);
            }
        });

        jBtnCloseSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnCloseSearch.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCloseSearch.setText("Close");
        jBtnCloseSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCloseSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCloseSearchMouseExited(evt);
            }
        });
        jBtnCloseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSearchPanelLayout = new javax.swing.GroupLayout(jSearchPanel);
        jSearchPanel.setLayout(jSearchPanelLayout);
        jSearchPanelLayout.setHorizontalGroup(
            jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jSearchPanelLayout.createSequentialGroup()
                        .addComponent(jBtnLotNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jBtnCloseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jSearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabelLotNo)
                        .addGap(50, 50, 50)
                        .addComponent(jTxtSearchLotNo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jSearchPanelLayout.setVerticalGroup(
            jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSearchPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLotNo)
                    .addComponent(jTxtSearchLotNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLotNoSearch)
                    .addComponent(jBtnCloseSearch))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
      // Start, Button formatting
      jBtnLotNoSearch.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
      jBtnCloseSearch.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
      // End, Button formatting
    }//GEN-LAST:event_formWindowOpened

    private void jBtnLotNoSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLotNoSearchMouseEntered
      Button ob = new Button();
      ob.paint(getGraphics(), jBtnLotNoSearch, "Entry");
    }//GEN-LAST:event_jBtnLotNoSearchMouseEntered

    private void jBtnLotNoSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLotNoSearchMouseExited
      Button ob = new Button();
      ob.paint(getGraphics(), jBtnLotNoSearch, "Exit");
    }//GEN-LAST:event_jBtnLotNoSearchMouseExited

    private void jBtnCloseSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseSearchMouseEntered
      Button ob = new Button();
      ob.paint(getGraphics(), jBtnCloseSearch, "Entry");
    }//GEN-LAST:event_jBtnCloseSearchMouseEntered

    private void jBtnCloseSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseSearchMouseExited
      Button ob = new Button();
      ob.paint(getGraphics(), jBtnCloseSearch, "Exit");
    }//GEN-LAST:event_jBtnCloseSearchMouseExited

    private void jBtnLotNoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLotNoSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLotNoSearchActionPerformed

    private void jBtnCloseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCloseSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.FrameBorderStyle.osLookAndFeelDecorated;

            javax.swing.UIManager.setLookAndFeel("org.jb2011.lnf.beautyeye.BeautyEyeLookAndFeelWin");
            javax.swing.UIManager.put("RootPane.setupButtonVisible", false);

        } catch (javax.swing.UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchLotNumber dialog = new SearchLotNumber(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCloseSearch;
    private javax.swing.JButton jBtnLotNoSearch;
    private javax.swing.JLabel jLabelLotNo;
    private javax.swing.JPanel jSearchPanel;
    private javax.swing.JTextField jTxtSearchLotNo;
    // End of variables declaration//GEN-END:variables
}
